// AUTO-GENERATED by scripts/sprite-import.mjs from docs/assets/decorations.png — do not edit by hand.
import { C, type SpectrumColor } from 'zx-kit'

export const ROCKS_W = 40
export const ROCKS_H = 24

export const ROCKS_ROWS = [
  '..................wwW...................',
  '................wwwwWWw.................',
  '...............wwWWwwww.................',
  '..............wWWWwWwwcC................',
  '.............wwWwwWWw..cc...............',
  '.............wwWwwwcc...c...............',
  '.............wwwwcccc...c...............',
  '.......wWw..CCCcccCc....c..Ww...........',
  '......wwWwc.ccccccc......wwwww..........',
  '......wWwwcc.cccccc......wwwww..........',
  '.....wwwWw.c.cccccC.....wWwwwcCc........',
  '.....WWwCc..c.cccc.....cwwwcc..c........',
  '....wwwccc..c..ccc.....cccccc..c........',
  '....Wwcccc..c..c.c.www..cCcc...cc.......',
  '....wccCC...C..Cc.wwwWw..CcC....c.c.cc..',
  '...cccccc......c..Wwwwwc.Ccc....c.ccC...',
  'Cc.ccccc.........WWwWWcc.cc.....c.Ccc.c.',
  '.cCccccC....wwc..wwWwc..c.c...wc..cc.cC.',
  'ccc.CcCc.c.wwwwc.cCwcc..C....wwc...c.C..',
  'ccc...cC...WWWCC..CCc.c..C...WWwCc.cc.cC',
  '...cC.....Wwccc.C.cccc...C..Wwcccc......',
  '...cc..Cc.CCcC..C.Ccc.......wccccc..Cc..',
  '.......cc..Ccc......C...cc...Ccc....Cc..',
  '..............C..C.....cC.Cc............',
] as const

export const ROCKS_COLORS: Record<string, SpectrumColor> = {
  C: C.B_CYAN,
  W: C.B_WHITE,
  c: C.CYAN,
  w: C.WHITE,
}
