// AUTO-GENERATED by scripts/sprite-import.mjs from docs/assets/decorations-v2.png — do not edit by hand.
import { C, type SpectrumColor } from 'zx-kit'

export const ROCKS_W = 40
export const ROCKS_H = 24

export const ROCKS_ROWS = [
  '.....................WWW................',
  '...................wWWWWWw..............',
  '..................WWWWWWWWW.............',
  '.................WWWwwwWwCWW............',
  '.................WWwWwwwccwCc...........',
  '..........w.....wwwWWWWwccccc...........',
  '........wWWWw...wwwwwwwwccc.c...........',
  '......wWWWWWWW.wwwwwwwwwwcc.c...........',
  '.....WWWWWWWwWw.wwwwwwwwwcc....ww.......',
  '....WWWWwwwWwccw.wwwwwwwwwcc..wWWWw.....',
  '...wWwwWWwwwcccc...w.wwwww...WWWwWWW....',
  '...wwwwwwWwwcccc..WWw.www...WWWWWwwww...',
  '..wWwwwwwccwc...wWWWWW..w..wwwwwWcccc...',
  '..wwwwwcccccc..WWWWWwwWW..WWWWwwwcccc...',
  '..wwwwwccccc.WWWWwWWwccw..wwwwwwwcccc...',
  '..wwwwwccc...WwwWWWwccccc.wwwwwwwcc.cc..',
  '..wwwwwccc..WWWWWwWwccccc..wwwwwwcccc...',
  'W...wwwcc...wwwwwwwwccccc.....w.w..c....',
  'wwWw.......wwwwwwwwwc.cccc.WWw..g....www',
  '..c..wWW...wwwwwwwwwcc.cc.WWwc...g......',
  '.....Wwcc.WW.wwwwwwwc.c..wwwwccwwggw....',
  '....wwwcc.cCc.w...w.c....wwwwcc.wWc.....',
  '.....ww......WWw.....WWWw...c....c......',
  '.............wcc....ccccc..w............',
] as const

export const ROCKS_COLORS: Record<string, SpectrumColor> = {
  C: C.B_CYAN,
  W: C.B_WHITE,
  c: C.CYAN,
  g: C.GREEN,
  w: C.WHITE,
}
