// AUTO-GENERATED by scripts/sprite-import.mjs from docs/assets/decorations.png — do not edit by hand.
import { C, type SpectrumColor } from 'zx-kit'

export const SIGNPOST_W = 32
export const SIGNPOST_H = 40

export const SIGNPOST_ROWS = [
  '.............yYYYyY.............',
  '............YyyyyyY.............',
  '............Yyy.y.Y.............',
  '............Yyy.y.y.............',
  '................................',
  '..YYYYYYYYYyyYyYYyYyyYyyYyYyY...',
  '..yyRRRRrrRrRrrRrrRrrRrRRrRryY..',
  '..YyyRrRrrrrRrrr.rrrrrrrrrRrryyy',
  '..yyyrrrrrrrrrr..rrrrrrrrrrrrryY',
  '..YyRrrRrrRrRrrrrrRrrRrRrrRrrYy.',
  '..YyrrrRrrRrRrrrrrRrrRrrrrRyy...',
  '..........................r.y...',
  '............Yy.y..Y.............',
  '............Yyyy..y.............',
  '...yYYYYYYYyYYYYYYYYYYYYYYYYy...',
  '...yyyyyyyyyyyyyyyyyyyyyyyyyy...',
  '..YyrRrRrrRrRrrRrrRrrrrRrrRrY...',
  'yYRrrRrRrrRrRrr...RrrRRRrryyy...',
  'yyyrrrrrrrRrrrr..rRrrrrrrrryy...',
  '..YrrrrRrrRrrrrrrrRrrrrrrrRry...',
  '...YyRrRRrRrrRrRrrRrrRrRrrRyy...',
  '................................',
  '............yy....Yy............',
  '............yyy...yy............',
  '............yyyyy.yy............',
  '............yyY...yy............',
  '............Yy.yY.Yy............',
  '............yy.yy.yy............',
  '............yy.YY.yy............',
  '............yy.yY.yy............',
  '............yy.Yy.Yy............',
  '......yY....yyY.y.Yy............',
  '......YY....yyy.y.yy....y.......',
  '......yyyy..yYy.y.Yy..yyY.......',
  '........yy..yYyY..yy..yy........',
  '...YY...Yyy.YyyYY.Yy..yy...YY...',
  '.....Y...yy.Yyy.y.yyyyy..yyy....',
  '.....Yyy.yyyyyy....yyY..yyy.....',
  '......yy..yY.yy.yy.yy..yYy......',
  '..Yyy.yyY...yy..yyy...Yyy..Yyy..',
] as const

export const SIGNPOST_COLORS: Record<string, SpectrumColor> = {
  R: C.B_RED,
  Y: C.B_YELLOW,
  r: C.RED,
  y: C.YELLOW,
}
