// AUTO-GENERATED by scripts/sprite-import.mjs from docs/assets/decorations-v2.png — do not edit by hand.
import { C, type SpectrumColor } from 'zx-kit'

export const SIGNPOST_W = 32
export const SIGNPOST_H = 40

export const SIGNPOST_ROWS = [
  '...............wWW..............',
  '..............wWWWw.............',
  '..............wcccc.............',
  '..............grrr..............',
  '........wWWWWwrrrr..wWwwWWWw....',
  '.......wwwwwwwwwr.wwwwwwwwWww...',
  '........yyyyyyyyyyyyyyyyyyyyyw..',
  '........yyyyyyyyyyyyyyyyyyyy.yw.',
  '........yyyyyyyyyyyyyyyyyyyyy.yy',
  '........yyyy.yYyyyyYyyyyyyyyyyyy',
  '........yyyyyyyyyyyyyYyyyyyYyyy.',
  '........yyyyyyyyyYyyyYyyyyyyyy..',
  '................................',
  '...............rrr..............',
  '...wWWwwwwwwwwwrrr..wwwwwwww....',
  '...wwwCcwwcwwwwwwwWcwcwWwwcww...',
  '..wyyyyyyyyyyyyyYYyyyyyyyyyy....',
  '.yyyyyyyyyyyyyyyyyyyyyyyyyyy....',
  'yy.yyy.yyyyyyyyYyyyyyyy.y.yy....',
  '.y.yyyyyyyyyyyyyyyyyyyyYyyyy....',
  '..y.yyyyyyyyyyyyyyyyyyyyyyyy....',
  '...yyyyyyyyyyyyyyyyyyyyyyyyy....',
  '................................',
  '...............rrr..............',
  '..............rrrr..............',
  '..............rrrr..............',
  '..............wrrr..............',
  '..............wrrr..............',
  '..............wwrr..............',
  '..............wwrr..............',
  '..............yrrr..............',
  '..............wrrr..............',
  '...........g..wwrr..............',
  '...........g..wwrr..g.gg........',
  '............ggWrrrw..ggg........',
  '.........w.wgwWrrrcw.ggg........',
  '.......wWWwcwWWw...cwCwWWw......',
  '......wwwwWWWwCCw.wWwwcwwWWw....',
  '........CcCCwCwwWWcwWW...C......',
  '..............wwWw..c...........',
] as const

export const SIGNPOST_COLORS: Record<string, SpectrumColor> = {
  C: C.B_CYAN,
  W: C.B_WHITE,
  Y: C.B_YELLOW,
  c: C.CYAN,
  g: C.GREEN,
  r: C.RED,
  w: C.WHITE,
  y: C.YELLOW,
}
